services:

  api:
    container_name: api
    build:
      dockerfile: api.dockerfile
      context: ./apps
      target: local
    image: shared-schedule-api:local
    ports:
      - ${API_PORT:-8080}:8080
    depends_on:
      db: 
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", 'printf "GET /api/v1/health HTTP/1.1\r\nHost: localhost\r\n\r\n" | nc localhost 8080 | grep "health check ok"' ]
      start_period: 20s
      interval: 5s
      timeout: 20s
      retries: 50
    env_file:
      - ./apps/api/.env
    volumes:
      - ./apps:/var/www/html/apps

  web:
    container_name: web
    build:
      dockerfile: web.dockerfile
      context: ./apps
      target: local
    image: shared-schedule-web:local
    ports:
      - ${WEB_PORT:-3000}:3000
    depends_on:
      api: 
        condition: service_healthy
    env_file:
      - ./apps/web/.env
    volumes:
      - ./apps:/var/www/html/apps

  db:
    container_name: db
    build:
      context: ./db
      target: local
    image: shared-schedule-db:local
    environment:
      POSTGRES_DB: shared-schedule
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    ports:
    - ${DB_PORT:-5432}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "developer" ]
      start_period: 3s
      interval: 5s
      timeout: 20s
      retries: 30
    volumes:
      - ./db/data:/var/lib/postgresql/data

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "4318:4318"
      - "16686:16686"

  infra:
    container_name: infra
    build:
      context: ./infra
    image: shared-schedule-infra:local
    env_file:
    - ./infra/.env
    volumes:
    - ./infra/src:/home/terraform/infra

# volumes:
#   shared-schedule-data: